twig:
    file_name_pattern: '*.twig'
    globals:
        upload_skill_dir: '/upload/skill/'
        upload_stack_dir: '/upload/stack/'
        upload_me_dir: '/upload/me/'

when@test:
    twig:
        strict_variables: true
